services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    # TODO: Make sure this is localhost
    ports:
      - "8000:80"
    volumes:
      # Mount the print.php file to the container
      - ./php/print.php:/var/www/html/print.php
      # Mount the vendor folder to the container
      #- ./php/vendor:/var/www/html/vendor
      # Mount the uploads folder to the container
      - "./uploads/:/var/www/uploads/"
    environment:
      UPLOAD_DIR: /var/www/uploads/
  
  # Basic MariaDB container
  mariadb:
    image: mariadb:latest
    environment:
      # TODO: Change the passwords here to password hashes
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CyberPrint
      MYSQL_USER: cdc
      MYSQL_PASSWORD: cdc
    ports:
      # TODO: Make sure this is localhost
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  
  nginx:
    # Use the modsecurity image to add WAF to the nginx container
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./uploads/:/var/www/html/uploads/
    depends_on:
      - php
      - keycloak
    #  - ruby
    #  - nextjs

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: mariadb
      # TODO: Update this to the mariadb container name when in the main compose file
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
    volumes:
      - ./keycloak/CyberPrint.json:/opt/keycloak/data/import/CyberPrint.json
    # TODO: This is a development environment, can we use production?
    # TODO: Remove the import realm after the realm is in the db
    command: start-dev
    
  nodejs:
    build: 
      context: ./nextjs/business-website
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  mariadb_data: