services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KC_DB: mariadb
      # TODO: Update this to the mariadb container name when in the main compose file
      KC_DB_URL: jdbc:mariadb://192.168.1.101:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: 'true'
    volumes:
      - ./CyberPrint.json:/opt/keycloak/data/import/CyberPrint.json
    # TODO: This is a development environment, can we use production?
    # TODO: Remove the import realm after the realm is in the db
    command: start-dev --import-realm